# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `decombobulate` gem.
# Please instead update this file by running `bin/tapioca gem decombobulate`.


# source://decombobulate//lib/decombobulate/version.rb#3
class Decombobulate
  # @return [Decombobulate] a new instance of Decombobulate
  #
  # source://decombobulate//lib/decombobulate.rb#13
  def initialize(json); end

  # Returns the value of attribute headers.
  #
  # source://decombobulate//lib/decombobulate.rb#11
  def headers; end

  # Returns the value of attribute rows.
  #
  # source://decombobulate//lib/decombobulate.rb#11
  def rows; end

  # source://decombobulate//lib/decombobulate.rb#45
  def to_csv(file_name = T.unsafe(nil)); end

  private

  # source://decombobulate//lib/decombobulate.rb#142
  def group_columns(columns); end

  # source://decombobulate//lib/decombobulate.rb#158
  def group_keys(keys = T.unsafe(nil), previous_key = T.unsafe(nil)); end

  # source://decombobulate//lib/decombobulate.rb#69
  def json_to_csv(json = T.unsafe(nil), nested_name = T.unsafe(nil), depth: T.unsafe(nil)); end

  class << self
    # source://comma/4.7.0/lib/comma/object.rb#7
    def comma_formats; end
  end
end

# source://decombobulate//lib/decombobulate.rb#9
class Decombobulate::Error < ::StandardError
  class << self
    # source://comma/4.7.0/lib/comma/object.rb#7
    def comma_formats; end
  end
end

# source://decombobulate//lib/decombobulate/version.rb#4
Decombobulate::VERSION = T.let(T.unsafe(nil), String)
