# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `murmurhash3` gem.
# Please instead update this file by running `bin/tapioca gem murmurhash3`.


# source://murmurhash3//lib/murmurhash3/version.rb#1
module MurmurHash3; end

# source://murmurhash3//lib/murmurhash3/aliaser.rb#16
module MurmurHash3::Alias128
  class << self
    # @private
    #
    # source://murmurhash3//lib/murmurhash3/aliaser.rb#17
    def included(base); end
  end
end

# source://murmurhash3//lib/murmurhash3/aliaser.rb#2
module MurmurHash3::Alias32
  class << self
    # @private
    #
    # source://murmurhash3//lib/murmurhash3/aliaser.rb#3
    def included(base); end
  end
end

# source://murmurhash3//lib/murmurhash3/native_murmur.rb#8
module MurmurHash3::Native128
  include ::MurmurHash3::Alias128
  extend ::MurmurHash3::Alias128
  extend ::MurmurHash3::Native128

  def murmur3_128_fmix(_arg0); end
  def murmur3_128_int32_hash(*_arg0); end
  def murmur3_128_int64_hash(*_arg0); end
  def murmur3_128_str_base64digest(*_arg0); end
  def murmur3_128_str_digest(*_arg0); end
  def murmur3_128_str_hash(*_arg0); end
  def murmur3_128_str_hexdigest(*_arg0); end

  class << self
    def fmix(_arg0); end
    def int32_hash(*_arg0); end
    def int64_hash(*_arg0); end
    def str_base64digest(*_arg0); end
    def str_digest(*_arg0); end
    def str_hash(*_arg0); end
    def str_hexdigest(*_arg0); end
  end
end

# source://murmurhash3//lib/murmurhash3/native_murmur.rb#5
module MurmurHash3::Native32
  include ::MurmurHash3::Alias32
  extend ::MurmurHash3::Alias32
  extend ::MurmurHash3::Native32

  def murmur3_32_fmix(_arg0); end
  def murmur3_32_int32_hash(*_arg0); end
  def murmur3_32_int64_hash(*_arg0); end
  def murmur3_32_str_base64digest(*_arg0); end
  def murmur3_32_str_digest(*_arg0); end
  def murmur3_32_str_hash(*_arg0); end
  def murmur3_32_str_hexdigest(*_arg0); end

  class << self
    def fmix(_arg0); end
    def int32_hash(*_arg0); end
    def int64_hash(*_arg0); end
    def str_base64digest(*_arg0); end
    def str_digest(*_arg0); end
    def str_hash(*_arg0); end
    def str_hexdigest(*_arg0); end
  end
end

# source://murmurhash3//lib/murmurhash3.rb#7
MurmurHash3::V128 = MurmurHash3::Native128

# source://murmurhash3//lib/murmurhash3.rb#6
MurmurHash3::V32 = MurmurHash3::Native32

# source://murmurhash3//lib/murmurhash3/version.rb#2
MurmurHash3::VERSION = T.let(T.unsafe(nil), String)
