# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `nio4r` gem.
# Please instead update this file by running `bin/tapioca gem nio4r`.


# New I/O for Ruby
#
# source://nio4r//lib/nio/version.rb#8
module NIO
  class << self
    # NIO implementation, one of the following (as a string):
    # * select: in pure Ruby using Kernel.select
    # * libev: as a C extension using libev
    # * java: using Java NIO
    #
    # source://nio4r//lib/nio.rb#21
    def engine; end

    # @return [Boolean]
    #
    # source://nio4r//lib/nio.rb#25
    def pure?(env = T.unsafe(nil)); end
  end
end

# source://nio4r//lib/nio.rb#59
NIO::ENGINE = T.let(T.unsafe(nil), String)

# source://nio4r//lib/nio/version.rb#9
NIO::VERSION = T.let(T.unsafe(nil), String)
