# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sixarm_ruby_unaccent` gem.
# Please instead update this file by running `bin/tapioca gem sixarm_ruby_unaccent`.


# String extensions.
#
# source://sixarm_ruby_unaccent//lib/sixarm_ruby_unaccent/string.rb#6
class String
  include ::Comparable

  # Replace a string's accented characters with unaccented characters.
  #
  # @example
  #   s = "Å Ç ß"
  #   s.unaccent = > "AA C ss"
  # @return [String] a string that has no accents
  #
  # source://sixarm_ruby_unaccent//lib/sixarm_ruby_unaccent/string.rb#16
  def unaccent; end

  # Replace a string's accented characters with unaccented characters,
  # by using string `#each_char` to iterate on characters.
  #
  # @example
  #   s = "Å Ç ß"
  #   s.unaccent_via_each_char = > "AA C ss"
  # @return [String] a string that has no accents
  #
  # source://sixarm_ruby_unaccent//lib/sixarm_ruby_unaccent/string.rb#42
  def unaccent_via_each_char; end

  # Replace a string's accented characters with unaccented characters,
  # by using string `#scan` to iterate on characters.
  #
  # @example
  #   s = "Å Ç ß"
  #   s.unaccent_via_scan = > "AA C ss"
  # @return [String] a string that has no accents
  #
  # source://sixarm_ruby_unaccent//lib/sixarm_ruby_unaccent/string.rb#29
  def unaccent_via_scan; end

  # Replace a string's accented characters with unaccented characters,
  # by using string `#split` and `#map` to iterate on characters.
  #
  # @example
  #   s = "Å Ç ß"
  #   s.unaccent_via_split_map = > "AA C ss"
  # @return [String] a string that has no accents
  #
  # source://sixarm_ruby_unaccent//lib/sixarm_ruby_unaccent/string.rb#55
  def unaccent_via_split_map; end
end

# source://sixarm_ruby_unaccent//lib/sixarm_ruby_unaccent/string.rb#61
String::ACCENTMAP = T.let(T.unsafe(nil), Hash)
