#!/usr/bin/env ruby

# require 'english'
require "rubocop"

ADDED_OR_MODIFIED = /A|AM|^M/.freeze

changed_files = `git status --porcelain`.split(/\n/).
  filter_map { |file_name_with_status|
      file_name_with_status.split(" ")[1] if ADDED_OR_MODIFIED.match?(file_name_with_status)
    }.
    select { |file_name|
      File.extname(file_name) == ".rb"
    }.join(" ")

system("rubocop -a #{changed_files}") unless changed_files.empty?

exit $?.to_s[-1].to_i
