development:
  url: neo4j://0.0.0.0:7687
  username: neo4j
  password: password

# test:
#   url: neo4j://0.0.0.0:7687
#   username: neo4j
#   password: password

test:
  url: RAISE_ENV["NEO4J_URL"]
  username: RAILS_ENV["NEO4J_USERNAME"]
  password: RAILS_ENV["NEO4J_PASSWORD"]

production:
  url:
    - RAILS_ENV["NEO4J_URL"]
  username: RAILS_ENV["NEO4J_USERNAME"]
  password: RAILS_ENV["NEO4J_PASSWORD"]
