name: Ruby

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install CuRL
      run: sudo apt-get install libcurl4-openssl-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.4
        bundler-cache: true
    - name: Lint with Rubocop
      run: bundle exec rubocop
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install CuRL
      run: sudo apt-get install libcurl4-openssl-dev
    - name: Install Vips
      run: sudo apt install libvips libvips-tools libvips-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.4
        bundler-cache: true
        redis-version: 7
    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3 --deployment
    - name: Run tests
      run: bundle exec rails test
